### ISSUE TITLE
Aligner running successfully but not creating Praat TextGrids , only creating 00v.txt

### ISSUE THREAD

**Issue by dbanka** [prosodylab/Prosodylab-Aligner#65] opened 2017-11-28 12:37 UTC
I ran this command in ubuntu after following the installation steps 
python3 -m aligner -r eng.zip -a data/ -d eng.dict

It is not giving any error but it is giving this as the response:
OOV word(s): see 'OOV.txt'.

No praat textgrids got created in the data directory. Only step I did differently in  the installation is that I installed scipy (1.0.0) instead of version 0.16.1 because it was giving errors while installation,

Where am I going wrong?

**Comment by kylebgorman** [comment] 2017-11-28 18:54
This is working as intended: you need to deal with the out of vocabulary
words (read the file `OOV.txt` as it says) and add them and their
pronunciations to your pronunciation dictionary, then retry. Like any
speech product, this can't handle out-of-vocabulary words (i.e., words it
doesn't know how to pronounce).

**Comment by kylebgorman** [comment] 2018-02-22 18:13
Closing issue

**Closed by kylebgorman** 2018-02-22 18:13 UTC
